### ISSUE TITLE
OSError: cannot open resource

### ISSUE THREAD

**Issue by hyperific** [rikfair/photoshow#4]
Running this on a Raspberry Pi 3A+ with the 32 bit desktop version of Buster.

python3 -m photoshow "/home/pi/Desktop/Slideshow_Images"
Presenting photoshow
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/.local/lib/python3.7/site-packages/photoshow/__main__.py", line 27, in <module>
    photoshow.present(sys.argv[1])
  File "/home/pi/.local/lib/python3.7/site-packages/photoshow/_photoshow.py", line 326, in present
    parameters = _get_parameters(path, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/photoshow/_photoshow.py", line 226, in _get_parameters
    _FONT_BIG: ImageFont.truetype(font_path, 40),
  File "/home/pi/.local/lib/python3.7/site-packages/PIL/ImageFont.py", line 996, in truetype
    return freetype(font)
  File "/home/pi/.local/lib/python3.7/site-packages/PIL/ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/pi/.local/lib/python3.7/site-packages/PIL/ImageFont.py", line 249, in __init__
    font, size, index, encoding, layout_engine=layout_engine
OSError: cannot open resource

The line numbers might be offset by 1 from my workaround.
I think the problem is in _get_parameters() 
`if` not font_path:
   font_path = 'arial.ttf'
`
arial.ttf isn't in the photoshow directory so ImageFont didn't know what to open. I won't be needing captions so I just hard coded it to point to a font in /usr/share/fonts/truetype/ which resolved my issue. I suppose I also could have resolved it by putting arial.ttf in /.local/python3.7/site-packages/photoshow/

**Comment by rikfair** [comment]
Sorry about that and thanks for raising the issue.
It wasn't necessary for the code to require a font when captions aren't being shown. It now checks the captions parameter to see if they are required before setting the font.
Fixed in 1.0.8
